# TODO: Write tests <30-11-23> 
# TODO: There should be a transformation of `MeasuredTransferFunction` to `TransferFunctionRealization`, which would
# take the same pixel-size as the measurement. <26-08-24> 
# TODO: Generating the OTF/PSF should be allowed only on the `TransferFunctionRealization` and there should be methods
# that allow to supply a `TransferFunction` with a pixel-size, but it should only construct the
# `TransferFunctionRealization` and leave the method alone <26-08-24> 


# FIX: This should be completely removed... It is not useful... We use a sampledOTF for something different than
# a sampled PSF... <26-08-24> 
# @doc raw"""
# `N`-dimensional transfer function realization. You can fix the pixels sizes (`Δxy`) and sample the transfer function on
# your sensor and optical system setup.
# """
# abstract type SampledTransferFunction{N} end

# TODO: A sampled OTF could be also created by a PSFModel or measurement... This could be done by letting there be
# a FromPSF<:ModelOpticalTransfer and the SampledOTF is created as a Fourier transform of the PSF evaluation...
# <26-08-24> 

# FIX: How about the measured transfer function, is it compatible with this view of the API <26-08-24> 

struct SampledOTF{N}
    "physical illumination pattern"
    transfer::OpticalTransferFunction{N}
    "pixel dimensions"
    Δxy::PixelSize{N}
    "center coordinate of the sample (useful for modulation methods such as SIM.)"
    center::Coordinate{N}
end

# NOTE: step 1 - fill in the pixel-size
SampledOTF(tf::OpticalTransferFunction{N}, Δxy::Length, args...) where {N} = SampledOTF(tf, fillsize(Δxy, N), args...)
# NOTE: step 2 - default center (ones)
SampledOTF(tf::OpticalTransferFunction{N}, Δxy::PixelSize{N}) where {N} = SampledOTF(tf, Δxy, ntuple(_ -> 1, Val(N)))

# FIX: Fix the docs!!! <26-08-24> 
@doc """
    otf(sampled_otf, wh)
    otf(sampled_otf, img)

Generate an otf array for the given transfer function with the size `wh` (size of `img`) and with a pixel distance of `Δxy`

!!! note
    The pixel size/distance (`Δxy`) is required for a [model transfer function](@ref ModelTransferFunction) and optional
    for a [`MeasuredTransferFunction`](@ref). If the pixel size/distance is not supplied to the
    [`MeasuerdTransferFunction`](@ref), it is assumed to be the same as in the measurement.

# Arguments
* `tf::TransferFunction`: transfer function (model/measured) to generate the OTF for
* `wh::Tuple{Integer, Integer}` or `wh::Integer`: (width, height) of the generated OTF. `wh` ↦ `(wh, wh)` if `wh isa
    Integer`.
* `Δxy::Tuple{Length, Length}` or `Δxy::Length`: Separation of pixels in the ``x`` and ``y`` dimensions of the generated
    OTF image. `Δxy` ↦ `(Δxy, Δxy)` if `Δxy isa Length`. (default: pixel distance from the measurement for a 
    [`MeasuredTransferFunction`](@ref))
* `δ::Tuple = (0,0)`: shift of the OTF in the image plane in pixels. This is useful for some algorithms, e.g. in 
    structured illumination microscopy reconstruction algorithms.
"""
# TODO: This should be shifted for a PSF that is real <15-09-23> 
function otf(
    tf::SampledOTF{N},
    wh::Indices{N}
) where {N}
    # TODO: This should instead be generated by a util function <26-08-24> 
    fxs, fys = ndgrid(fftfreq(wh[1], 1 / tf.Δxy[1]), fftfreq(wh[2], 1 / tf.Δxy[2]))
    # PERF: Could be speeded up using `ShiftedArrays` with integer `δ` <20-07-23> 
    return otf.(tf,
        fxs .- tf.center[1] / (tf.Δxy[1] * wh[1]),
        fys .- tf.center[2] / (tf.Δxy[2] * wh[2]))
end



# otf.jl
otf(tfr::SampledOTF, args...; varargs...) = otf(tfr.transfer, args..., tfr.Δxy; varargs...)
mtf(tfr::SampledOTF, args...; varargs...) = mtf(tfr.transfer, args..., tfr.Δxy; varargs...)
ptf(tfr::SampledOTF, args...; varargs...) = ptf(tfr.transfer, args..., tfr.Δxy; varargs...)
otf_support(tfr::SampledOTF, args...; varargs...) = otf_support(tfr.transfer, args..., tfr.Δxy; varargs...)
