# TODO: Write tests <30-11-23> 
# TODO: There should be a transformation of `MeasuredTransferFunction` to `TransferFunctionRealization`, which would
# take the same pixel-size as the measurement. <26-08-24> 
# TODO: Generating the OTF/PSF should be allowed only on the `TransferFunctionRealization` and there should be methods
# that allow to supply a `TransferFunction` with a pixel-size, but it should only construct the
# `TransferFunctionRealization` and leave the method alone <26-08-24> 


# FIX: This should be completely removed... It is not useful... We use a sampledOTF for something different than
# a sampled PSF... <26-08-24> 
# @doc raw"""
# `N`-dimensional transfer function realization. You can fix the pixels sizes (`Δxy`) and sample the transfer function on
# your sensor and optical system setup.
# """
# abstract type SampledTransferFunction{N} end

# TODO: A sampled OTF could be also created by a PSFModel or measurement... This could be done by letting there be
# a FromPSF<:ModelOpticalTransfer and the SampledOTF is created as a Fourier transform of the PSF evaluation...
# <26-08-24> 

# FIX: How about the measured transfer function, is it compatible with this view of the API <26-08-24> 

struct SampledOTF{N,OTF<:OpticalTransferFunction{N}}
    "physical illumination pattern"
    transfer::OTF
    "pixel dimensions"
    Δxy::PixelSize{N}
    "center coordinate of the sample (useful for modulation methods such as SIM.)"
    center::Coordinate{N}
end

# NOTE: step 1 - fill in the pixel-size
SampledOTF(tf::OpticalTransferFunction{N}, Δxy::Length, args...) where {N} = SampledOTF(tf, fillsize(Δxy, N), args...)
# NOTE: step 2 - default center (ones)
SampledOTF(tf::OpticalTransferFunction{N}, Δxy::PixelSize{N}) where {N} = SampledOTF(tf, Δxy, ntuple(_ -> 1, Val(N)))

# FIX: Fix the docs!!! <26-08-24> 
@doc """
    otf(sampled_otf, wh)
    otf(sampled_otf, img)

Generate an otf array for the given transfer function with the size `wh` (size of `img`) and with a pixel distance of `Δxy`

!!! note
    The pixel size/distance (`Δxy`) is required for a [model transfer function](@ref ModelTransferFunction) and optional
    for a [`MeasuredTransferFunction`](@ref). If the pixel size/distance is not supplied to the
    [`MeasuerdTransferFunction`](@ref), it is assumed to be the same as in the measurement.

# Arguments
* `tf::TransferFunction`: transfer function (model/measured) to generate the OTF for
* `wh::Tuple{Integer, Integer}` or `wh::Integer`: (width, height) of the generated OTF. `wh` ↦ `(wh, wh)` if `wh isa
    Integer`.
* `Δxy::Tuple{Length, Length}` or `Δxy::Length`: Separation of pixels in the ``x`` and ``y`` dimensions of the generated
    OTF image. `Δxy` ↦ `(Δxy, Δxy)` if `Δxy isa Length`. (default: pixel distance from the measurement for a 
    [`MeasuredTransferFunction`](@ref))
* `δ::Tuple = (0,0)`: shift of the OTF in the image plane in pixels. This is useful for some algorithms, e.g. in 
    structured illumination microscopy reconstruction algorithms.
"""
# TODO: Add a method for a single index... i.e. indexing of a sampled OTF. This should perhaps be an overload of the
# `Base.getindex` function <29-08-24> 
# TODO: Test this. Not covered by tests and should return only the data under `inds` so it should be more performant
# when I do not need the full array. <29-08-24> 
function otf(
    OT::Type{<:Number},
    tf::SampledOTF{N},
    inds::Indices{N}
) where {N}
    # FIX: Is this truly as simple as using the length of the range? Shouldn't it be different if the range is shifted? <26-08-24> 
    # TODO: This should instead be generated by a util function <26-08-24> 
    fxs, fys = freqs(inds, tf.Δxy, tf.center)
    # PERF: Could be speeded up using `ShiftedArrays` with integer `δ` <20-07-23> 
    return attenuation.(OT, tf.transfer, fxs, fys)
end
function otf(
    tf::SampledOTF{N,OTF},
    inds::Indices{N}
) where {N,OTF}
    return otf(preferred_type(OTF), tf, inds)
end

function otf(OT::Type{<:Number}, tf::SampledOTF{N,OTF}, wh::Tuple{Integer,Integer}, args...; vargs...) where {N,OTF}
    return otf(OT, tf, (1:wh[1], 1:wh[2]), args...; vargs...) # FIX: Are these truly the correct indices? <26-08-24> 
end
function otf(tf::SampledOTF{N,OTF}, wh::Tuple{Integer,Integer}, args...; vargs...) where {N,OTF}
    return otf(preferred_type(OTF), tf, (1:wh[1], 1:wh[2]), args...; vargs...) # FIX: Are these truly the correct indices? <26-08-24> 
end

# @doc raw"""
#     otf(tf, wh, [Δxy]; δ=(0, 0))
#     otf(tf, img, [Δxy];...)
#
# Generate an otf for the given transfer function with the size `wh` (size of `img`) and with a pixel distance of `Δxy`
#
# !!! note
#     The pixel size/distance (`Δxy`) is required for a [model transfer function](@ref ModelTransferFunction) and optional
#     for a [`MeasuredTransferFunction`](@ref). If the pixel size/distance is not supplied to the
#     [`MeasuerdTransferFunction`](@ref), it is assumed to be the same as in the measurement.
#
# # Arguments
# * `tf::TransferFunction`: transfer function (model/measured) to generate the OTF for
# * `wh::Tuple{Integer, Integer}` or `wh::Integer`: (width, height) of the generated OTF. `wh` ↦ `(wh, wh)` if `wh isa
#     Integer`.
# * `Δxy::Tuple{Length, Length}` or `Δxy::Length`: Separation of pixels in the ``x`` and ``y`` dimensions of the generated
#     OTF image. `Δxy` ↦ `(Δxy, Δxy)` if `Δxy isa Length`. (default: pixel distance from the measurement for a 
#     [`MeasuredTransferFunction`](@ref))
# * `δ::Tuple = (0,0)`: shift of the OTF in the image plane in pixels. This is useful for some algorithms, e.g. in 
#     structured illumination microscopy reconstruction algorithms.
# """
# # TODO: This should be shifted for a PSF that is real <15-09-23> 
# function otf(
#     tf::ModelOTF,
#     wh::Tuple{Integer,Integer},
#     Δxy::Tuple{Length,Length};
#     δ::Tuple{<:Real,<:Real}=(0, 0)
# )
#     fxs, fys = ndgrid(fftfreq(wh[1], 1 / Δxy[1]), fftfreq(wh[2], 1 / Δxy[2]))
#     # PERF: Could be speeded up using `ShiftedArrays` with integer `δ` <20-07-23> 
#     return otf.(tf,
#         fxs .- δ[1] / (Δxy[1] * wh[1]),
#         fys .- δ[2] / (Δxy[2] * wh[2]))
# end

# FIX: This does not work with `img` for since `args...` expects at least one argument it seems <19-12-24> 
otf(tf::SampledOTF{N,OTF}, img::AbstractArray{OT,N}, args...; vargs...) where {OT,OTF,N} = otf(OT, tf, size(img), args...; vargs...)
otf(OT::Type{<:Number}, tf::SampledOTF{N,OTF}, img::AbstractArray{T,N}, args...; vargs...) where {T,OTF,N} = otf(OT, tf, size(img), args...; vargs...)

@doc raw"""
 modulation transfer function
 """
mtf(OT::Type{<:Real}, tf::SampledOTF, args...; vargs...) = real(otf(Complex{OT}, tf, args...; vargs...))
# NOTE: Choose the correct real type <26-08-24> 
function mtf(tf::SampledOTF{N,OTF}, args...; vargs...) where {N,OTF}
    tf_type = preferred_type(OTF)
    if tf_type <: Complex
        evaluation_type = tf_type.parameters[1]
    else
        @assert tf_type <: Real "Preferred type of evaluation is `<:Real`"
        evaluation_type = tf_type
    end
    mtf(evaluation_type, tf, args...; vargs...)
end

@doc raw"""
 phase transfer function
 """
ptf(OT::Type{<:Real}, tf::SampledOTF, args...; vargs...) = imag(otf(Complex{OT}, tf, args...; vargs...))
# NOTE: Choose the correct real type <26-08-24> 
function ptf(tf::SampledOTF{N,OTF}, args...; vargs...) where {N,OTF}
    tf_type = preferred_type(OTF)
    if tf_type <: Complex
        evaluation_type = tf_type.parameters[1]
    else
        @assert tf_type <: Real "Preferred type of evaluation is `<:Real`"
        evaluation_type = tf_type
    end
    ptf(evaluation_type, tf, args...; vargs...)
end

# TODO: Catch method error that `cutoff` is not implemented. Then use the default array generation method. This is for
# types that do not implement the method. It should be optional. <29-08-24> 
# TODO: Docs <28-08-24> 
@traitfn function support(tf::SampledOTF{N,OTF}, wh::Indices{N}; a=0) where {N,OTF;RadiallySymmetric{OTF}}
    cut_f = cutoff(tf.transfer, a)
    fxs, fys = freqs(wh, tf.Δxy, tf.center)
    return hypot.(fxs, fys) .<= cut_f
end
@traitfn function support(tf::SampledOTF{N,OTF}, wh::Indices{N}; a=0) where {N,OTF;!RadiallySymmetric{OTF}}
    # TODO: The contents of the note should be explicitly and clearly stated in the documentation <28-08-24> 
    # NOTE: When talking about the actual support, we want to get where the OTF, is positive and when we have a specific
    # belief attenuation `a`, we want to include it in the support. <28-08-24> 
    # TODO: Is this correct? How about `Complex` should this be the `abs` or `real`? <28-08-24>
    a == 0 ? otf(tf, wh) .> 0 : otf(tf, wh) .>= a
end
support(tf::SampledOTF{N,OTF}, wh::Tuple{Integer,Integer}; a=0) where {N,OTF} = support(tf, (1:wh[1], 1:wh[2]); a)
support(tf::SampledOTF{N,OTF}, img::AbstractArray; a=0) where {N,OTF} = support(tf, size(img); a)

# TODO: Docs <28-08-24> 
function overlap(tf_1::SampledOTF{N,OTF1}, tf_2::SampledOTF{N,OTF2}, wh::Indices{N}; a_1=0, a_2=0) where {N,OTF1,OTF2}
    return support(tf_1, wh; a=a_1) .* support(tf_2, wh; a=a_2)
end
overlap(tf_1::SampledOTF{N,OTF1}, tf_2::SampledOTF{N,OTF2}, wh::Tuple{Integer,Integer}; a_1=0, a_2=0) where {N,OTF1,OTF2} = overlap(tf_1, tf_2, (1:wh[1], 1:wh[2]); a_1, a_2)
overlap(tf_1::SampledOTF{N,OTF1}, tf_2::SampledOTF{N,OTF2}, img::AbstractArray; a_1=0, a_2=0) where {N,OTF1,OTF2} = overlap(tf_1, tf_2, size(img); a_1, a_2)

# TODO: Consider implementing a `cutoff` function here as well that gives the pixel radius of the support. Look below
# for an example of where it could be useful. We could instead of the attenuation determined support give a radius
# determined one <29-08-24> 

# FIX: When implemented, can remove the `size` <19-12-24> 
# FIX: `gray` should not be here as it introduces type instability. Could it be defined somehow in `ImageFiltering` that I can copy here? <19-12-24> 
# FIX: Currenty returns `ComplexF64` regardless of `T`. This should be changed such that it returns the same type if
# this is expected during the transfer <19-12-24> 
@doc raw"""
    apply(tf::SampledOTF, img::AbstractArray)
Apply the transfer function `tf` to the image `img`, i.e. simulate the transfer through the optical system.

# Examples
```jldoctest; filter = r"\s*Downloading artifact:.*\n" => s"" 
julia> otf_model = IdealOTFwithCurvature(488u"nm", 1.4, 1.0, 0.9);

julia> sampled_otf = SampledOTF(otf_model, 61u"nm");

julia> img = testimage("moonsurface.tiff");

julia> blurred_img = apply(sampled_otf, img);
```
"""
apply(tf::SampledOTF{N}, img::AbstractArray{T,N}) where {N,T} = ifft(fft(gray.(img)) .* otf(tf, size(img))) 

# FIX: Add support for N-dim <30-11-23> 
# @traitfn function otf_support(
#     tf::TF,
#     wh::Tuple{Integer,Integer},
#     Δxy::Tuple{Length,Length};
#     ρ::Union{Real,Tuple{Real,Real}}=(0.0, 1.0),
#     inclusive::Union{Bool,Tuple{Bool,Bool}}=(true, true)
# ) where {TF <: TransferFunction; RadiallySymmetric{TF}}
#     if ρ isa Real
#         ρ = ρ > 0 ? (0, ρ) : (1 + ρ, 1)
#     end
#     inclusive = inclusive isa Bool ? (inclusive, inclusive) : inclusive
#
#     fxs, fys = ndgrid(fftfreq(wh[1], 1 / Δxy[1]), fftfreq(wh[2], 1 / Δxy[2]))
#     left = inclusive[1] ? ρ[1] * cutoff_frequency(tf) .<= hypot.(fxs, fys) : ρ[1] * cutoff_frequency(tf) .< hypot.(fxs, fys)
#     right = inclusive[2] ? hypot.(fxs, fys) .< ρ[2] * cutoff_frequency(tf) : hypot.(fxs, fys) .< ρ[2] * cutoff_frequency(tf)
#     return left .* right
# end
# otf_support(tf, wh::Integer, args...; varargs...) = otf_support(tf, (wh, wh), args...; varargs...)
# otf_support(tf, wh::Tuple, Δxy::Length, args...; varargs...) = otf_support(tf, wh, (Δxy, Δxy), args...; varargs...)
# otf_support(tf, img::AbstractArray, args...; varargs...) = otf_support(tf, size(img), args...; varargs...)
