# TODO: Write tests <30-11-23> 
# TODO: There should be a transformation of `MeasuredTransferFunction` to `TransferFunctionRealization`, which would
# take the same pixel-size as the measurement. <26-08-24> 
# TODO: Generating the OTF/PSF should be allowed only on the `TransferFunctionRealization` and there should be methods
# that allow to supply a `TransferFunction` with a pixel-size, but it should only construct the
# `TransferFunctionRealization` and leave the method alone <26-08-24> 


# FIX: This should be completely removed... It is not useful... We use a sampledOTF for something different than
# a sampled PSF... <26-08-24> 
# @doc raw"""
# `N`-dimensional transfer function realization. You can fix the pixels sizes (`Δxy`) and sample the transfer function on
# your sensor and optical system setup.
# """
# abstract type SampledTransferFunction{N} end

# TODO: A sampled OTF could be also created by a PSFModel or measurement... This could be done by letting there be
# a FromPSF<:ModelOpticalTransfer and the SampledOTF is created as a Fourier transform of the PSF evaluation...
# <26-08-24> 

# FIX: How about the measured transfer function, is it compatible with this view of the API <26-08-24> 

struct SampledOTF{N,OTF<:OpticalTransferFunction{N}}
    "physical illumination pattern"
    transfer::OTF
    "pixel dimensions"
    Δxy::PixelSize{N}
    "center coordinate of the sample (useful for modulation methods such as SIM.)"
    center::Coordinate{N}
end

# NOTE: step 1 - fill in the pixel-size
SampledOTF(tf::OpticalTransferFunction{N}, Δxy::Length, args...) where {N} = SampledOTF(tf, fillsize(Δxy, N), args...)
# NOTE: step 2 - default center (ones)
SampledOTF(tf::OpticalTransferFunction{N}, Δxy::PixelSize{N}) where {N} = SampledOTF(tf, Δxy, ntuple(_ -> 1, Val(N)))

# FIX: Fix the docs!!! <26-08-24> 
@doc """
    otf(sampled_otf, wh)
    otf(sampled_otf, img)

Generate an otf array for the given transfer function with the size `wh` (size of `img`) and with a pixel distance of `Δxy`

!!! note
    The pixel size/distance (`Δxy`) is required for a [model transfer function](@ref ModelTransferFunction) and optional
    for a [`MeasuredTransferFunction`](@ref). If the pixel size/distance is not supplied to the
    [`MeasuerdTransferFunction`](@ref), it is assumed to be the same as in the measurement.

# Arguments
* `tf::TransferFunction`: transfer function (model/measured) to generate the OTF for
* `wh::Tuple{Integer, Integer}` or `wh::Integer`: (width, height) of the generated OTF. `wh` ↦ `(wh, wh)` if `wh isa
    Integer`.
* `Δxy::Tuple{Length, Length}` or `Δxy::Length`: Separation of pixels in the ``x`` and ``y`` dimensions of the generated
    OTF image. `Δxy` ↦ `(Δxy, Δxy)` if `Δxy isa Length`. (default: pixel distance from the measurement for a 
    [`MeasuredTransferFunction`](@ref))
* `δ::Tuple = (0,0)`: shift of the OTF in the image plane in pixels. This is useful for some algorithms, e.g. in 
    structured illumination microscopy reconstruction algorithms.
"""
# TODO: This should be shifted for a PSF that is real <15-09-23> 
function otf(
    OT::Type{<:Number},
    tf::SampledOTF{N},
    wh::Indices{N}
) where {N}
    # FIX: Is this truly as simple as using the length of the range? Shouldn't it be different if the range is shifted? <26-08-24> 
    # TODO: This should instead be generated by a util function <26-08-24> 
    fxs, fys = ndgrid(fftfreq(length(wh[1]), 1 / tf.Δxy[1]), fftfreq(length(wh[2]), 1 / tf.Δxy[2]))
    # PERF: Could be speeded up using `ShiftedArrays` with integer `δ` <20-07-23> 
    return otf.(OT, tf.transfer,
        fxs .- (tf.center[1] - 1) / (tf.Δxy[1] * length(wh[1])), # TODO: Is this center shifting correct? <26-08-24> 
        fys .- (tf.center[2] - 1) / (tf.Δxy[2] * length(wh[2])))
end
function otf(
    tf::SampledOTF{N,OTF},
    wh::Indices{N}
) where {N,OTF}
    return otf(preferred_type(OTF), tf, wh)
end

function otf(OT::Type{<:Number}, tf::SampledOTF{N,OTF}, wh::Tuple{Integer,Integer}, args...; vargs...) where {N,OTF}
    return otf(OT, tf, (1:wh[1], 1:wh[2]), args...; vargs...) # FIX: Are these truly the correct indices? <26-08-24> 
end
function otf(tf::SampledOTF{N,OTF}, wh::Tuple{Integer,Integer}, args...; vargs...) where {N,OTF}
    return otf(preferred_type(OTF), tf, (1:wh[1], 1:wh[2]), args...; vargs...) # FIX: Are these truly the correct indices? <26-08-24> 
end

# @doc raw"""
#     otf(tf, wh, [Δxy]; δ=(0, 0))
#     otf(tf, img, [Δxy];...)
#
# Generate an otf for the given transfer function with the size `wh` (size of `img`) and with a pixel distance of `Δxy`
#
# !!! note
#     The pixel size/distance (`Δxy`) is required for a [model transfer function](@ref ModelTransferFunction) and optional
#     for a [`MeasuredTransferFunction`](@ref). If the pixel size/distance is not supplied to the
#     [`MeasuerdTransferFunction`](@ref), it is assumed to be the same as in the measurement.
#
# # Arguments
# * `tf::TransferFunction`: transfer function (model/measured) to generate the OTF for
# * `wh::Tuple{Integer, Integer}` or `wh::Integer`: (width, height) of the generated OTF. `wh` ↦ `(wh, wh)` if `wh isa
#     Integer`.
# * `Δxy::Tuple{Length, Length}` or `Δxy::Length`: Separation of pixels in the ``x`` and ``y`` dimensions of the generated
#     OTF image. `Δxy` ↦ `(Δxy, Δxy)` if `Δxy isa Length`. (default: pixel distance from the measurement for a 
#     [`MeasuredTransferFunction`](@ref))
# * `δ::Tuple = (0,0)`: shift of the OTF in the image plane in pixels. This is useful for some algorithms, e.g. in 
#     structured illumination microscopy reconstruction algorithms.
# """
# # TODO: This should be shifted for a PSF that is real <15-09-23> 
# function otf(
#     tf::ModelOTF,
#     wh::Tuple{Integer,Integer},
#     Δxy::Tuple{Length,Length};
#     δ::Tuple{<:Real,<:Real}=(0, 0)
# )
#     fxs, fys = ndgrid(fftfreq(wh[1], 1 / Δxy[1]), fftfreq(wh[2], 1 / Δxy[2]))
#     # PERF: Could be speeded up using `ShiftedArrays` with integer `δ` <20-07-23> 
#     return otf.(tf,
#         fxs .- δ[1] / (Δxy[1] * wh[1]),
#         fys .- δ[2] / (Δxy[2] * wh[2]))
# end

otf(tf::SampledOTF{N,OTF}, img::AbstractArray{OT,N}, args...; vargs...) where {OT,OTF,N} = otf(OT, tf, size(img), args...; vargs...)
otf(OT::Type{<:Number}, tf::SampledOTF{N,OTF}, img::AbstractArray{T,N}, args...; vargs...) where {T,OTF,N} = otf(OT, tf, size(img), args...; vargs...)

@doc raw"""
 modulation transfer function
 """
mtf(OT::Type{<:Real}, tf::SampledOTF, args...; vargs...) = real(otf(Complex{OT}, tf, args...; vargs...))
# NOTE: Choose the correct real type <26-08-24> 
function mtf(tf::SampledOTF{N,OTF}, args...; vargs...) where {N,OTF}
    tf_type = preferred_type(OTF)
    if tf_type <: Complex
        evaluation_type = tf_type.parameters[1]
    else
        @assert tf_type <: Real "Preferred type of evaluation is `<:Real`"
        evaluation_type = tf_type
    end
    mtf(evaluation_type, tf, args...; vargs...)
end

@doc raw"""
 phase transfer function
 """
ptf(OT::Type{<:Real}, tf::SampledOTF, args...; vargs...) = imag(otf(Complex{OT}, tf, args...; vargs...))
# NOTE: Choose the correct real type <26-08-24> 
function ptf(tf::SampledOTF{N,OTF}, args...; vargs...) where {N,OTF}
    tf_type = preferred_type(OTF)
    if tf_type <: Complex
        evaluation_type = tf_type.parameters[1]
    else
        @assert tf_type <: Real "Preferred type of evaluation is `<:Real`"
        evaluation_type = tf_type
    end
    ptf(evaluation_type, tf, args...; vargs...)
end

# FIX: Not the correct API... <26-08-24> 
otf_support(tf::SampledOTF, args...; vargs...) = otf_support(tf.transfer, args...; vargs...)
